version: '3.8'

services:
  ragtime:
    container_name: ragtime
    build: .
    ports:
      - 8887:5000
    command: >
      sh -c "
        if [ ! -f .env ]; then
          echo '# Default environment variables' > .env;
          echo 'DEBUG=False' >> .env;
          echo 'SECRET_KEY=default_secret_key_change_me' >> .env;
        fi &&
        gunicorn --workers 4 --bind 0.0.0.0:5000 --timeout 240 wsgi:application
      "
    volumes:
      - ./UI/backend:/app
      - ./logs:/app/logs
      - ./classes.py:/app/app/services/classes.py
    networks:
       - MyNetwork

  frontend:
    container_name: frontend
    build: ./UI/
    ports:
      - 8080:8080
    volumes:
      - ./UI:/app
      - /app/node_modules
    networks:
      - MyNetwork
    command: >
      sh -c "
        if [ ! -f .env ]; then
          echo '# Default environment variables' > .env;
          echo 'VUE_APP_API_URL=http://localhost:8887' >> .env;
        fi &&
        npm run serve
      "

networks:
   MyNetwork:
     name: mynetwork