services:
  ragtime:
    container_name: ragtime
    build: .
    ports:
      - 8887:5000
    command: >
      sh -c "
        mkdir -p /app &&
        if [ ! -f /app/.env ]; then
          echo '# Default environment variables' > /app/.env;
        fi &&
        gunicorn --workers 4 --bind 0.0.0.0:5000 --timeout 240 wsgi:application
      "    
    volumes:
      - ./project/backend:/app
      - ./logs:/app/logs
      - ./classes.py:/app/app/services/classes.py
    networks:
      - MyNetwork

  frontend:
    container_name: frontend
    build: ./project/
    ports:
      - 8080:8080
    volumes:
      - ./project:/app
      - /app/node_modules
      - ./.env:/app/.env
    networks:
      - MyNetwork
    command: npm run serve

networks:
  MyNetwork:
    name: mynetwork
