<template>
  <p v-if="llmAnswer" class="answer-meta">
    Generated by: {{ llmAnswer.name }} ({{ formattedDate }})
  </p>
</template>

<script>
import { formatDate } from '@/utils/dateFormatter';

export default {
  name: 'AnswerMeta',
  props: {
    llmAnswer: { type: Object, required: true }
  },
  computed: {
    formattedDate() {
      return formatDate(this.llmAnswer.timestamp);
    }
  }
};
</script>

<style scoped>
.answer-meta {
  font-size: 12px;
  color: #666;
  margin-top: 5px;
}
</style>