<template>
  <v-card class="answer-item mb-4 golden-answer">
    <v-card-text>
      <v-expand-transition>
        <div v-if="isEditing" class="answer-edit">
          <v-textarea
            v-model="editedText"
            label="Edit answer"
            auto-grow
            rows="4"
            outlined
          ></v-textarea>
          <v-card-actions class="justify-end mt-2">
            <v-btn color="primary" @click="saveAnswer" class="mr-2">
              <v-icon left>fa-solid fa-floppy-disk</v-icon>
              Save
            </v-btn>
            <v-btn color="error" @click="cancelEdit">
              <v-icon left>fa-sharp-duotone fa-solid fa-xmark</v-icon>
              Cancel
            </v-btn>
          </v-card-actions>
        </div>
      </v-expand-transition>
      
      <div v-if="!isEditing" class="answer-display">
        <div v-html="markedDownText"></div>
        <AnswerActions 
          :isEditing="isEditing"
          @edit="startEditing"
          @delete="deleteAnswer"
        />
      </div>
      
      <v-divider class="my-3"></v-divider>
      
      <div class="answer-meta text-caption">
        <p>Generated by: {{ generatedBy }} on ({{ formattedDate }})</p>
        <p v-if="answer.llm_answer.name !== 'Human' && answer.llm_answer.cost !== undefined && answer.llm_answer.cost !== null" class="font-weight-medium">
          Cost: ${{ formatNumber(answer.llm_answer.cost) }}
        </p>
        <p v-if="answer.llm_answer.duration !== undefined && answer.llm_answer.duration !== null" class="font-weight-medium">
          Duration: {{ formatNumber(answer.llm_answer.duration) }}s
        </p>
        <p v-if="answer.human_modified" class="font-italic">
          Last modified by human: {{ formatDate(answer.human_modified_timestamp) }}
        </p>
      </div>
    </v-card-text>
  </v-card>
</template>

<script>
import { formatDate } from '@/utils/dateFormatter';
import AnswerActions from './AnswerActions.vue';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import TurndownService from 'turndown';

export default {
  name: 'AnswerItem',
  components: {
    AnswerActions
  },
  props: {
    answer: { type: Object, required: true },
    index: { type: Number, required: true }
  },
  data() {
    return {
      isEditing: false,
      editedText: '',
      turndownService: new TurndownService()
    };
  },
  computed: {
    generatedBy() {
      const name = this.answer.llm_answer.name;
      // if (this.answer.human_modified && !name.includes('(modified by human)')) {
      //   return `${name} (modified by human)`;
      // }
      return name;
    },
    formattedDate() {
      return formatDate(this.answer.llm_answer.timestamp);
    },
    markedDownText() {
      return DOMPurify.sanitize(this.answer.text);
    }
  },
  methods: {
    formatDate,
    formatNumber(value) {
      return value !== null && value !== undefined ? value.toFixed(6) : 'N/A';
    },
    startEditing() {
      this.isEditing = true;
      this.editedText = this.turndownService.turndown(this.answer.text);
    },
    saveAnswer() {
      const updatedAnswer = {
        ...this.answer,
        text: marked(this.editedText),
        human_modified: true,
        human_modified_timestamp: new Date().toISOString(),
        eval: { ...this.answer.eval, human: 1 } // Ensure human eval is always 1
      };
      this.$emit('update', this.index, updatedAnswer);
      this.isEditing = false;
    },
    cancelEdit() {
      this.isEditing = false;
    },
    deleteAnswer() {
      this.$emit('delete', this.index);
    }
  },
  created() {
    // Ensure answer.eval.human is always 1
    if (!this.answer.eval || this.answer.eval.human !== 1) {
      this.$emit('update', this.index, {
        ...this.answer,
        eval: { ...this.answer.eval, human: 1 }
      });
    }
  }
};
</script>

<style scoped>
/* .golden-answer {
  border: 2px solid gold !important;
  background-color: rgba(255, 215, 0, 0.1) !important;
} */

.golden-answer::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  box-shadow: 0 0 10px rgba(255, 215, 0, 0.5);
  pointer-events: none;
}

.answer-meta {
  color: rgba(0, 0, 0, 0.6);
}

.answer-meta .font-weight-medium {
  color: #1976D2;
}
</style>